version: '3.7'

services:
  ansible-control:
    image: hoal/ansible-control
    build: .
    tty: true
    environment: 
        - ANSIBLE_HOST_KEY_CHECKING=false
    volumes:
      - ./hosts:/etc/ansible/hosts
      - ./access:/usr/src
      - ./sshconfig:/root/.ssh/config
      - ~/.ssh/id_rsa_alpm:/root/.ssh/id_rsa